# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prono',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='prono',
            name='time',
            field=models.CharField(max_length=40),
        ),
    ]
