# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180622_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='result',
        ),
        migrations.AddField(
            model_name='prono',
            name='result_away',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prono',
            name='result_home',
            field=models.CharField(default=5, max_length=10),
            preserve_default=False,
        ),
    ]
