# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180630_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='id',
        ),
        migrations.AddField(
            model_name='prono',
            name='check_in',
            field=models.AutoField(default=datetime.datetime(2018, 6, 29, 21, 25, 19, 553368, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
