# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20180630_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='check_in',
        ),
        migrations.AddField(
            model_name='prono',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),

        ),
    ]
