# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20180630_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='prono',
            name='match_date',
            field=models.CharField(default=5, max_length=40),
            preserve_default=False,
        ),
    ]
