# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20180630_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='prono',
            name='win_odd',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
    ]
