# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(

            name='Prono',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400)),
                ('chance', models.CharField(max_length=40)),
                ('odd1', models.CharField(max_length=40)),
                ('oddX', models.CharField(max_length=40)),
                ('odd2', models.CharField(max_length=40)),
                ('win_odd', models.CharField(max_length=20)),
                ('result_overall', models.CharField(max_length=20)),
                ('match_result', models.CharField(max_length=40)),
            ]
        )
    ]
