# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upto_date', models.DateTimeField(blank=True, null=True)),
                ('counter_lost_odd', models.CharField(max_length=20)),
                ('counter_won_odd', models.CharField(max_length=20)),
                ('counter_lose', models.CharField(max_length=20)),
                ('counter_win', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='prono',
            name='id',
        ),
        migrations.AlterField(
            model_name='prono',
            name='teams',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
