# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180817_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='id',
        ),
        migrations.AlterField(
            model_name='prono',
            name='teams',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
