# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180621_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prono',
            name='teams',
            field=models.CharField(max_length=400),
        ),
    ]
