# Generated by Django 2.0.9 on 2018-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180817_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='id',
        ),
        migrations.AlterField(
            model_name='prono',
            name='teams',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
