# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_prono_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prono',
            name='id',
        ),
        migrations.AddField(
            model_name='prono',
            name='check_in',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
