# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_prono_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prono',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
